name: Deploy coffee_shop-frontend

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t akshitmittal20/coffee_shop_img_frontend  . 


      - name: Publish Image to docker hub
        run: docker push akshitmittal20/coffee_shop_img_frontend:latest
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull akshitmittal20/coffee_shop_img_frontend:latest
      - name: Delete old container
        run: docker rm -f coffee_shop_container_frontend
      - name: Run Docker Container
        run: docker run -d -p 5174:5174 --name coffee_shop_container_frontend akshitmittal20/coffee_shop_img_frontend